export const tahminler = {
  "Kullanici #1": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Fluminense",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Fluminense", "Manchester City"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #2": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #3": {
    groups: {
      A: ["Al Ahly", "Porto", "Palmeiras", "Inter Miami"],
      B: ["Atletico Madrid", "PSG", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "LA FC", "Flamengo", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Ulsan", "Mamelodi"],
      G: ["Al Ain", "Manchester City", "Juventus", "Wydad AC"],
      H: ["Al Hilal", "Real Madrid", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Al Ain",
        "Real Madrid",
      ],
      sf: ["Palmeiras", "Porto", "Inter Miami", "PSG"],
      final: ["Atletico Madrid", "Bayern Münih"],
      champion: "Atletico Madrid",
    },
  },
  "Kullanici #4": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["Atletico Madrid", "PSG", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Al Hilal",
      ],
      sf: ["Atletico Madrid", "Bayern Münih", "Inter Milan", "Manchester City"],
      final: ["Bayern Münih", "Manchester City"],
      champion: "Manchester City",
    },
  },
  "Kullanici #5": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Seattle Sounders", "Atletico Madrid", "Botafogo"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Flamengo", "Chelsea", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Urawa", "Monterrey"],
      F: ["Dortmund", "Mamelodi", "Fluminense", "Ulsan"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Pachuca", "RB Salzburg", "Al Hilal"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Boca Juniors",
        "River Plate",
        "Inter Milan",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Juventus", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #6": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "Urawa", "Monterrey", "River Plate"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Inter Milan", "Manchester City", "Real Madrid"],
      final: ["Manchester City", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #7": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Atletico Madrid", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #8": {
    groups: {
      A: ["Palmeiras", "Porto", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Juventus",
      ],
      sf: ["PSG", "Bayern Münih", "Dortmund", "Juventus"],
      final: ["PSG", "Juventus"],
      champion: "PSG",
    },
  },
  "Kullanici #9": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Flamengo", "Chelsea", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Pachuca", "Al Hilal", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Benfica",
        "Chelsea",
        "Inter Milan",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Atletico Madrid", "Bayern Münih", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #10": {
    groups: {
      A: ["Palmeiras", "Porto", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Fluminense",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #11": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Dortmund", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #12": {
    groups: {
      A: ["Palmeiras", "Inter Miami", "Porto", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Seattle Sounders", "Botafogo"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "LA FC", "Flamengo", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Fluminense", "Dortmund", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Boca Juniors",
        "River Plate",
        "Inter Milan",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Manchester City"],
      final: ["PSG", "Manchester City"],
      champion: "Manchester City",
    },
  },
  "Kullanici #13": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Mamelodi", "Fluminense", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #14": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "PSG",
        "Bayern Münih",
        "Benfica",
        "Chelsea",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "River Plate", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #15": {
    groups: {
      A: ["Palmeiras", "Porto", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Flamengo", "Chelsea", "ES Tunis", "LA FC"],
      E: ["River Plate", "Monterrey", "Inter Milan", "Urawa"],
      F: ["Fluminense", "Dortmund", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Al Hilal", "Real Madrid", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Benfica",
        "River Plate",
        "Monterrey",
        "Fluminense",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Real Madrid", "Al Hilal"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #16": {
    groups: {
      A: ["Palmeiras", "Porto", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "River Plate", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #17": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["Atletico Madrid", "PSG", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Atletico Madrid",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["Atletico Madrid", "Manchester City", "Juventus", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #18": {
    groups: {
      A: ["Al Ahly", "Porto", "Inter Miami", "Palmeiras"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Bayern Münih",
        "Benfica",
        "Chelsea",
        "Inter Milan",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Chelsea", "Inter Milan"],
      final: ["PSG", "Bayern Münih"],
      champion: "Bayern Münih",
    },
  },
  "Kullanici #19": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Urawa", "Monterrey"],
      F: ["Fluminense", "Dortmund", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Al Hilal", "Real Madrid", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Chelsea", "Manchester City"],
      final: ["Bayern Münih", "Manchester City"],
      champion: "Manchester City",
    },
  },
  "Kullanici #20": {
    groups: {
      A: ["Palmeiras", "Porto", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["Inter Miami", "PSG", "Bayern Münih", "Manchester City"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #21": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Mamelodi", "Fluminense", "Ulsan"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Al Hilal", "RB Salzburg", "Real Madrid", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Juventus",
      ],
      sf: ["PSG", "Bayern Münih", "Dortmund", "Manchester City"],
      final: ["Bayern Münih", "Manchester City"],
      champion: "Bayern Münih",
    },
  },
  "Kullanici #22": {
    groups: {
      A: ["Palmeiras", "Al Ahly", "Porto", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "Urawa", "River Plate", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "PSG",
        "Botafogo",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #23": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #24": {
    groups: {
      A: ["Palmeiras", "Porto", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Mamelodi", "Fluminense", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #25": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #26": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #27": {
    groups: {
      A: ["Inter Miami", "Porto", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "ES Tunis", "Flamengo", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["Atletico Madrid", "Chelsea", "Dortmund", "Real Madrid"],
      final: ["Atletico Madrid", "Real Madrid"],
      champion: "Atletico Madrid",
    },
  },
  "Kullanici #28": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Juventus",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Manchester City"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #29": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #30": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Pachuca", "RB Salzburg", "Al Hilal"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #31": {
    groups: {
      A: ["Porto", "Inter Miami", "Al Ahly", "Palmeiras"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "Urawa", "River Plate", "Monterrey"],
      F: ["Dortmund", "Ulsan", "Fluminense", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Dortmund", "Manchester City"],
      final: ["PSG", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #32": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #33": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #34": {
    groups: {
      A: ["Porto", "Al Ahly", "Palmeiras", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #35": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Mamelodi", "Fluminense", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Dortmund",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #36": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "LA FC",
        "Inter Milan",
        "Ulsan",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Atletico Madrid", "Bayern Münih", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #37": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Pachuca", "RB Salzburg", "Al Hilal"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Benfica",
        "Flamengo",
        "Chelsea",
        "Inter Milan",
        "Manchester City",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Manchester City"],
      final: ["Bayern Münih", "Manchester City"],
      champion: "Manchester City",
    },
  },
  "Kullanici #38": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "LA FC", "Flamengo", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #39": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Inter Milan", "Manchester City", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #40": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Flamengo", "Chelsea", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Botafogo",
        "Bayern Münih",
        "Flamengo",
        "River Plate",
        "Inter Milan",
        "Manchester City",
        "Juventus",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Manchester City"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #41": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["Atletico Madrid", "PSG", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["Atletico Madrid", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #42": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Dortmund", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #43": {
    groups: {
      A: ["Inter Miami", "Al Ahly", "Porto", "Palmeiras"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "Monterrey", "Urawa", "River Plate"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Pachuca", "Al Hilal"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Dortmund",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["Manchester City", "Real Madrid"],
      champion: "Manchester City",
    },
  },
  "Kullanici #44": {
    groups: {
      A: ["Porto", "Al Ahly", "Palmeiras", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Seattle Sounders", "Botafogo"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "Inter Milan",
        "Dortmund",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Benfica", "Real Madrid"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #45": {
    groups: {
      A: ["Inter Miami", "Porto", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Inter Miami",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["Inter Miami", "PSG", "Manchester City", "Real Madrid"],
      final: ["Manchester City", "Real Madrid"],
      champion: "Manchester City",
    },
  },
  "~Borges": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Juventus",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Juventus"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #47": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Atletico Madrid", "Juventus", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #48": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Manchester City"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #49": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "Chelsea",
        "Ulsan",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["Bayern Münih", "Dortmund", "Manchester City", "Real Madrid"],
      final: ["Bayern Münih", "Manchester City"],
      champion: "Manchester City",
    },
  },
  "Kullanici #50": {
    groups: {
      A: ["Inter Miami", "Porto", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Inter Miami",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #51": {
    groups: {
      A: ["Inter Miami", "Porto", "Al Ahly", "Palmeiras"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Mamelodi", "Fluminense", "Ulsan"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "Dortmund",
        "Manchester City",
        "Juventus",
      ],
      sf: ["Atletico Madrid", "Bayern Münih", "Manchester City", "Juventus"],
      final: ["PSG", "Juventus"],
      champion: "PSG",
    },
  },
  "Kullanici #52": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Bayern Münih",
    },
  },
  "Kullanici #53": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #54": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["Atletico Madrid", "PSG", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "LA FC", "Flamengo", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "Chelsea",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["Atletico Madrid", "Dortmund", "Manchester City", "Real Madrid"],
      final: ["Atletico Madrid", "Bayern Münih"],
      champion: "Atletico Madrid",
    },
  },
  "Kullanici #55": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Pachuca", "Al Hilal"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #56": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Juventus",
      ],
      sf: ["PSG", "Bayern Münih", "Dortmund", "Manchester City"],
      final: ["PSG", "Manchester City"],
      champion: "Manchester City",
    },
  },
  "Kullanici #57": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #58": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Manchester City"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #59": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Ulsan", "Mamelodi"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Pachuca", "Al Hilal", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Boca Juniors",
        "River Plate",
        "Dortmund",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["Bayern Münih", "Boca Juniors", "Juventus", "Real Madrid"],
      final: ["Bayern Münih", "Boca Juniors"],
      champion: "Boca Juniors",
    },
  },
  "Kullanici #60": {
    groups: {
      A: ["Palmeiras", "Al Ahly", "Inter Miami", "Porto"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Dortmund", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Bayern Münih",
    },
  },
  "Kullanici #61": {
    groups: {
      A: ["Porto", "Al Ahly", "Inter Miami", "Palmeiras"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["Atletico Madrid", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["Manchester City", "Real Madrid"],
      champion: "Manchester City",
    },
  },
  "Kullanici #62": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "LA FC", "Flamengo", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["Inter Miami", "PSG", "Inter Milan", "Real Madrid"],
      final: ["Manchester City", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #63": {
    groups: {
      A: ["Porto", "Al Ahly", "Inter Miami", "Palmeiras"],
      B: ["PSG", "Atletico Madrid", "Seattle Sounders", "Botafogo"],
      C: ["Bayern Münih", "Benfica", "Auckland City", "Boca Juniors"],
      D: ["Chelsea", "LA FC", "Flamengo", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Dortmund", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "Manchester City",
    },
  },
  "Kullanici #64": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #65": {
    groups: {
      A: ["Palmeiras", "Inter Miami", "Porto", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Flamengo", "Chelsea", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Fluminense", "Dortmund", "Ulsan", "Mamelodi"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "River Plate",
        "Inter Milan",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #66": {
    groups: {
      A: ["Inter Miami", "Palmeiras", "Porto", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #67": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["Atletico Madrid", "PSG", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Flamengo", "Chelsea", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "PSG",
        "Bayern Münih",
        "Benfica",
        "Dortmund",
        "Manchester City",
        "Juventus",
        "Real Madrid",
        "Al Hilal",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["Manchester City", "Real Madrid"],
      champion: "Manchester City",
    },
  },
  "Kullanici #68": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Al Hilal", "Real Madrid", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Chelsea", "Manchester City"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #69": {
    groups: {
      A: ["Inter Miami", "Porto", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "Pachuca", "RB Salzburg"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Benfica",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Chelsea", "Manchester City"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #70": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #71": {
    groups: {
      A: ["Palmeiras", "Inter Miami", "Al Ahly", "Porto"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Mamelodi", "Fluminense", "Ulsan"],
      G: ["Juventus", "Manchester City", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "River Plate", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #72": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Dortmund", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #73": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Atletico Madrid", "Dortmund", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #74": {
    groups: {
      A: ["Palmeiras", "Inter Miami", "Porto", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Fluminense", "Dortmund", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Manchester City"],
      champion: "Manchester City",
    },
  },
  "Kullanici #75": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Urawa", "Monterrey"],
      F: ["Fluminense", "Dortmund", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Pachuca", "Real Madrid", "RB Salzburg", "Al Hilal"],
    },
    knockout: {
      qf: [
        "PSG",
        "Boca Juniors",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Boca Juniors", "River Plate", "Dortmund"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #76": {
    groups: {
      A: ["Inter Miami", "Porto", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Bayern Münih",
        "Benfica",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Atletico Madrid", "Dortmund", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #77": {
    groups: {
      A: ["Inter Miami", "Porto", "Palmeiras", "Al Ahly"],
      B: ["Atletico Madrid", "PSG", "Seattle Sounders", "Botafogo"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["LA FC", "Chelsea", "Flamengo", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Inter Miami",
        "PSG",
        "Bayern Münih",
        "LA FC",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #78": {
    groups: {
      A: ["Palmeiras", "Al Ahly", "Porto", "Inter Miami"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Urawa", "Inter Milan", "Monterrey"],
      F: ["Fluminense", "Mamelodi", "Dortmund", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Fluminense",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "River Plate", "Manchester City", "Real Madrid"],
      final: ["Manchester City", "Real Madrid"],
      champion: "Manchester City",
    },
  },
  "Kullanici #79": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "LA FC", "Flamengo", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["Porto", "PSG", "Manchester City", "Real Madrid"],
      final: ["Manchester City", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #80": {
    groups: {
      A: ["Inter Miami", "Palmeiras", "Porto", "Al Ahly"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Flamengo", "Chelsea", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Fluminense", "Mamelodi", "Dortmund", "Ulsan"],
      G: ["Juventus", "Manchester City", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Inter Miami",
        "PSG",
        "Bayern Münih",
        "Benfica",
        "Inter Milan",
        "Fluminense",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Bayern Münih",
    },
  },
  "Kullanici #81": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Benfica",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
      ],
      sf: ["PSG", "Inter Milan", "Dortmund", "Manchester City"],
      final: ["PSG", "Manchester City"],
      champion: "Manchester City",
    },
  },
  "Kullanici #82": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Fluminense", "Dortmund", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["Porto", "PSG", "Manchester City", "Real Madrid"],
      final: ["Porto", "PSG"],
      champion: "PSG",
    },
  },
  "Kullanici #83": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Ulsan", "Fluminense", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Inter Miami",
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "Inter Milan",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Inter Milan", "Manchester City", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #84": {
    groups: {
      A: ["Inter Miami", "Palmeiras", "Porto", "Al Ahly"],
      B: ["Atletico Madrid", "PSG", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Flamengo", "Chelsea", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Atletico Madrid", "Manchester City", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #85": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Ulsan", "Fluminense", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Chelsea", "Dortmund", "Real Madrid"],
      final: ["PSG", "Dortmund"],
      champion: "PSG",
    },
  },
  "Kullanici #86": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["Manchester City", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #87": {
    groups: {
      A: ["Palmeiras", "Porto", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Bayern Münih",
        "Benfica",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #88": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Boca Juniors",
        "Benfica",
        "Chelsea",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #89": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "Monterrey", "River Plate", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["Bayern Münih", "Inter Milan", "Manchester City", "Real Madrid"],
      final: ["Manchester City", "Real Madrid"],
      champion: "Manchester City",
    },
  },
  "Kullanici #90": {
    groups: {
      A: ["Porto", "Palmeiras", "Al Ahly", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Atletico Madrid", "Inter Milan", "Juventus"],
      final: ["PSG", "Atletico Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #91": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #92": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["Atletico Madrid", "Botafogo", "PSG", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "ES Tunis", "LA FC"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Pachuca", "Al Hilal"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["Porto", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["Porto", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #93": {
    groups: {
      A: ["Porto", "Inter Miami", "Al Ahly", "Palmeiras"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "Monterrey", "Urawa", "River Plate"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "Al Ahly",
        "PSG",
        "Atletico Madrid",
        "Benfica",
        "Chelsea",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["Porto", "PSG", "Inter Milan", "Real Madrid"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #94": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Flamengo", "Chelsea", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "River Plate",
        "Inter Milan",
        "Manchester City",
        "Juventus",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Manchester City"],
      final: ["PSG", "Manchester City"],
      champion: "PSG",
    },
  },
  "Kullanici #95": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Urawa", "Monterrey"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "Chelsea",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Dortmund", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #96": {
    groups: {
      A: ["Porto", "Inter Miami", "Palmeiras", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Ulsan", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Inter Milan", "Manchester City", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #97": {
    groups: {
      A: ["Al Ahly", "Inter Miami", "Porto", "Palmeiras"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "ES Tunis", "Flamengo", "LA FC"],
      E: ["Inter Milan", "Monterrey", "River Plate", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Juventus", "Manchester City", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Benfica",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Dortmund", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #98": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Atletico Madrid",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Bayern Münih"],
      champion: "PSG",
    },
  },
  "Kullanici #99": {
    groups: {
      A: ["Inter Miami", "Porto", "Al Ahly", "Palmeiras"],
      B: ["Atletico Madrid", "PSG", "Seattle Sounders", "Botafogo"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Ulsan", "Fluminense", "Mamelodi"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "Inter Miami",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Manchester City",
        "Juventus",
        "Real Madrid",
      ],
      sf: ["PSG", "Atletico Madrid", "Manchester City", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Real Madrid",
    },
  },
  "Kullanici #100": {
    groups: {
      A: ["Porto", "Palmeiras", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Botafogo", "Atletico Madrid", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Porto",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
  "Kullanici #101": {
    groups: {
      A: ["Porto", "Al Ahly", "Palmeiras", "Inter Miami"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["River Plate", "Inter Milan", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "River Plate",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Manchester City", "Real Madrid"],
      final: ["Bayern Münih", "Real Madrid"],
      champion: "Bayern Münih",
    },
  },
  "Kullanici #102": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Boca Juniors", "Benfica", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "Monterrey", "River Plate", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Wydad AC", "Al Ain"],
      H: ["Real Madrid", "RB Salzburg", "Al Hilal", "Pachuca"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Chelsea",
        "Inter Milan",
        "Dortmund",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Inter Milan", "Real Madrid"],
      final: ["PSG", "Inter Milan"],
      champion: "PSG",
    },
  },
  "Kullanici #103": {
    groups: {
      A: ["Palmeiras", "Porto", "Inter Miami", "Al Ahly"],
      B: ["PSG", "Atletico Madrid", "Botafogo", "Seattle Sounders"],
      C: ["Bayern Münih", "Benfica", "Boca Juniors", "Auckland City"],
      D: ["Chelsea", "Flamengo", "LA FC", "ES Tunis"],
      E: ["Inter Milan", "River Plate", "Monterrey", "Urawa"],
      F: ["Dortmund", "Fluminense", "Mamelodi", "Ulsan"],
      G: ["Manchester City", "Juventus", "Al Ain", "Wydad AC"],
      H: ["Real Madrid", "Al Hilal", "RB Salzburg", "Pachuca"],
    },
    knockout: {
      qf: [
        "Palmeiras",
        "PSG",
        "Bayern Münih",
        "Flamengo",
        "Chelsea",
        "River Plate",
        "Manchester City",
        "Real Madrid",
      ],
      sf: ["PSG", "Bayern Münih", "Chelsea", "Real Madrid"],
      final: ["PSG", "Real Madrid"],
      champion: "PSG",
    },
  },
};
